declare const TemplateIOErrorMessages: {
    readonly EACCES: "access denied";
    readonly EIO: "an I/O error occurred";
    readonly ENOENT: "no such file or directory";
    readonly EEXIST: "file already exists";
    readonly ELOOP: "too many symbolic links encountered";
    readonly ENOTDIR: "no such directory";
    readonly EISDIR: "path is a directory";
    readonly EBADF: "invalid file descriptor";
    readonly EINVAL: "invalid value";
    readonly ENOTEMPTY: "directory not empty";
    readonly EPERM: "operation not permitted";
    readonly EROFS: "file system is read-only";
};
export declare const IOErrorMessages: typeof TemplateIOErrorMessages;
export declare function createIOError(code: keyof typeof IOErrorMessages, details?: string): NodeJS.ErrnoException;
export declare function createENOENT(path: string, syscall?: string): NodeJS.ErrnoException;
export declare function createENOTDIR(path: string, syscall?: string): NodeJS.ErrnoException;
export declare function createEISDIR(path: string, syscall?: string): NodeJS.ErrnoException;
export {};
