import { FileSystem, os, path, process as proc } from "./vfsUtil";
export const fs=new FileSystem();
proc.__setfs(fs);
export {process, os, path} from "./vfsUtil";
export const require=(module: string):any=>{
    if (module==="fs") return fs;
    if (module==="os") return os;
    if (module==="path") return path;
    return null;
};
export function fakeNodeEnvironment() {
    const g=globalThis as any;
    g.require=require;
    g.process=proc;
}
/*export default fs;
export function genExports() {
    let res="";
    for(let k in fs) {
        if (k==="default") continue;
        res+=`export const ${k}=fs.${k};\n`;
    }
    return res;
}*/
//---generated by genExports()----
